# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oRwjzAi81NColwWExsoeWt59Lg8ByFGZ
"""

#import lib
import networkx as nx
import matplotlib.pyplot as plt

#do friendship
G = nx.Graph()

edges = [("Father","Mother"),("Mother","Child"),("Child","Father")]
G.add_edges_from(edges)

#===================================================
#1. find the degree - dict()
print("1. The degree is : ", dict(G.degree()))

#2. what is the density - nx.density()
print("2. The density is : ", nx.density(G))

#3. what is the diameter
print("3. The diameter is : ", nx.diameter(G))

#4. find the average cluster
print("4. The average cluster is : ", nx.average_clustering(G))

#5. show the adjacency matrix
print("5. The adjacency matrix is : \n", nx.to_numpy_array(G))

#6. plot the graph
plt.figure(figsize=(8, 6))
nx.draw(G, with_labels=True, node_color='blue',
        node_size=2000, font_size=12, font_weight='bold',
        edge_color='gray', arrows=False)
plt.title("Family Friendship Graph")
plt.show()