# -*- coding: utf-8 -*-
"""untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/Raphaeled/2f84e2b31b15169d8a8ae32775cd0edd/untitled4.ipynb
"""

#import Lib
import networkx as nx
import matplotlib.pyplot as plt

#do friendship
G = nx.Graph()

edges = [("Father","Mother"),("Mother","Child"),("Child","Father")]
G.add_edges_from(edges)

#=========================================================
#1. find the degree - dict()
print("1. The degree is : ", dict(G.degree()))

#2. what is the density - nx.density()
print("2. The density is : ", nx.density(G))

#3. what is the diameter
print("3. The diameter is : ", nx.diameter(G))

#4. find the average cluster
print("4. The average cluster is : ", nx.average_clustering(G))

#5. show the adjacency matrix
print("5. The adjacency matrix is : \n", nx.to_numpy_array(G))

#6. plot the graph
print("6. The graph is displayed below:")
plt.figure(figsize=(8, 6))
nx.draw(G, with_labels=True, node_color='lightblue',
        node_size=1000, font_size=12, font_weight='bold')
plt.title("Family Friendship Graph")
plt.show()